drop database if exists renters;
create database renters;
use renters;

CREATE TABLE IF NOT EXISTS Login(
  Nick_L VARCHAR(15) NOT NULL PRIMARY KEY,
  email VARCHAR(45),
  contrasenia VARCHAR(100)
  );
  


CREATE TABLE IF NOT EXISTS Persona(
  Nick_U VARCHAR(15) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45),
  ApellidoP VARCHAR(45),
  ApellidoM VARCHAR(45),
  Genero VARCHAR(45),
  Fecha VARCHAR(45),
  Cel VARCHAR(45),
  Estado VARCHAR(45),
  Nick_L VARCHAR(15) NOT NULL,
  FOREIGN KEY (Nick_L)
  REFERENCES  Login(Nick_L)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    
    

CREATE TABLE IF NOT EXISTS Admon_Usua(
  Nick_AU VARCHAR(15) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45),
  ApellidoP VARCHAR(45),
  ApellidoM VARCHAR(45),
  Genero VARCHAR(45),
  Cel VARCHAR(45));


CREATE TABLE IF NOT EXISTS Tipo(
  idTipo INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45));


CREATE TABLE IF NOT EXISTS Login_Tipo(
  Nick_L VARCHAR(15) NOT NULL,
  idTipo INT NOT NULL,
    FOREIGN KEY (Nick_L)
    REFERENCES Login(Nick_L)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (idTipo)
    REFERENCES Tipo(idTipo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Delegacion(
  idDel INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45));


CREATE TABLE IF NOT EXISTS Direccion(
  idDir INT NOT NULL PRIMARY KEY,
  Colonia VARCHAR(45),
  CP INT,
  Calle VARCHAR(45),
  No_int INT,
  No_ext INT,
  idDel INT NOT NULL,
    FOREIGN KEY (idDel)
    REFERENCES Delegacion(idDel)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Persona_Dir(
  Nick_U VARCHAR(15) NOT NULL,
  idDir INT NOT NULL,
    FOREIGN KEY (Nick_U)
    REFERENCES Persona(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (idDir)
    REFERENCES Direccion(idDir)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS AdmonU_Usuario(
  Persona_Nick_U VARCHAR(15) NOT NULL,
  Admon_Usua_Nick_AU VARCHAR(15) NOT NULL,
    FOREIGN KEY (Persona_Nick_U)
    REFERENCES Persona(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Admon_Usua_Nick_AU)
    REFERENCES Admon_Usua(Nick_AU)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Owner(
  Nick_O VARCHAR(15) NOT NULL PRIMARY KEY,
  Nick_U VARCHAR(15) NOT NULL,
    FOREIGN KEY (Nick_U)
    REFERENCES Persona(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Catalogo_Servicios(
  idCS INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45));


CREATE TABLE IF NOT EXISTS Servicio(
  idServicio INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45),
  idCS INT NOT NULL,
    FOREIGN KEY (idCS)
    REFERENCES Catalogo_Servicios(idCS)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Owner_Ser(
  Nick_O VARCHAR(15) NOT NULL,
  idServicio INT NOT NULL,
    FOREIGN KEY (Nick_O)
    REFERENCES Owner(Nick_O)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (idServicio)
    REFERENCES Servicio(idServicio)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Admon_Ser(
  Nick_AS VARCHAR(15) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(45),
  ApellidoP VARCHAR(45),
  ApellidoM VARCHAR(45),
  Genero VARCHAR(45),
  Cel VARCHAR(45));


CREATE TABLE IF NOT EXISTS AdmonSer_Ser(
  idServicio INT NOT NULL,
  Nick_AS VARCHAR(15) NOT NULL,
    FOREIGN KEY (idServicio)
    REFERENCES Servicio(idServicio)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Nick_AS)
    REFERENCES Admon_Ser(Nick_AS)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Zona_Trabajo(
  idZT INT NOT NULL PRIMARY KEY,
  Estado VARCHAR(45),
  Ciudad VARCHAR(45),
  Delegacion VARCHAR(45));


CREATE TABLE IF NOT EXISTS Owner_ZT(
  Nick_O VARCHAR(15) NOT NULL,
  idZT INT NOT NULL,
    FOREIGN KEY (Nick_O)
    REFERENCES Owner(Nick_O)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (idZT)
    REFERENCES Zona_Trabajo(idZT)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Renter(
  Nick_R VARCHAR(15) NOT NULL PRIMARY KEY,
  Nick_U VARCHAR(15) NOT NULL,
    FOREIGN KEY (Nick_U)
    REFERENCES Persona(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Contrato(
  Clave VARCHAR(20) NOT NULL PRIMARY KEY,
  Fecha VARCHAR(45),
  Hora VARCHAR(45),
  Especificaciones VARCHAR(225),
  Clausulas VARCHAR(225),
  Nick_R VARCHAR(15) NOT NULL,
  Nick_U VARCHAR(15) NOT NULL,
  Nick_O VARCHAR(15) NOT NULL,
    FOREIGN KEY (Nick_R)
    REFERENCES Renter(Nick_R)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Nick_U)
    REFERENCES Renter(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Nick_O)
    REFERENCES Owner(Nick_O)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS AdmonSer_Contrato(
  Nick_AS VARCHAR(15) NOT NULL,
  Clave VARCHAR(20) NOT NULL,
    FOREIGN KEY (Nick_AS)
    REFERENCES Admon_Ser(Nick_AS)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Clave)
    REFERENCES Contrato(Clave)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



CREATE TABLE IF NOT EXISTS Horario_Trabajo(
  idHT INT NOT NULL PRIMARY KEY,
  Dia VARCHAR(45),
  Hora VARCHAR(45),
  Nick_O VARCHAR(15) NOT NULL,
    FOREIGN KEY (Nick_O)
    REFERENCES Owner(Nick_O)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    
    
CREATE TABLE IF NOT EXISTS Queja(
  id_Queja INT NOT NULL PRIMARY KEY,
  Descripcion VARCHAR(400),
  Clave VARCHAR(20) NOT NULL,
    FOREIGN KEY (Clave)
    REFERENCES Contrato(Clave)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Pago(
  idPago INT NOT NULL PRIMARY KEY,
  Banco VARCHAR(45) NULL,
  Fecha VARCHAR(45) NULL,
  Monto VARCHAR(45) NULL);


CREATE TABLE IF NOT EXISTS Catalogo_Tarjetas(
  id_Tar VARCHAR(45) NOT NULL PRIMARY KEY,
  Tipo VARCHAR(15),
  Nick_U VARCHAR(15) NOT NULL,
  idPago INT NOT NULL,
    FOREIGN KEY (Nick_U)
    REFERENCES Persona(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (idPago)
    REFERENCES Pago(idPago)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    
    
    
CREATE TABLE IF NOT EXISTS LoginTipo_Queja(
  id_Queja INT NOT NULL,
  Nick_U VARCHAR(15) NOT NULL,
  idTipo INT NOT NULL,
    FOREIGN KEY (id_Queja)
    REFERENCES Queja(id_Queja)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Nick_U)
    REFERENCES Persona(Nick_U)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (idTipo)
    REFERENCES Tipo(idTipo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
