-- MySQL Script generated by MySQL Workbench
-- Mon Sep  3 18:50:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `Nick_L` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Contrasenia` VARCHAR(45) NULL,
  PRIMARY KEY (`Nick_L`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Nick_U` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Fecha_Nac` DATE NULL,
  `Cel` VARCHAR(15) NULL,
  `No_Tar_Cred` VARCHAR(20) NULL,
  `Estado` VARCHAR(15) NULL,
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick_U`, `Login_Nick_L`),
  INDEX `fk_Usuario_Login1_idx` (`Login_Nick_L` ASC),
  CONSTRAINT `fk_Usuario_Login`
    FOREIGN KEY (`Login_Nick_L`)
    REFERENCES `mydb`.`Login` (`Nick_L`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admon_Usua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admon_Usua` (
  `Nick_AU` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  `ApellidoP` VARCHAR(25) NULL,
  `ApellidoM` VARCHAR(25) NULL,
  `Genero` VARCHAR(15) NULL,
  `Cel` VARCHAR(15) NULL,
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick_AU`, `Login_Nick_L`),
  INDEX `fk_Admon_Usua_Login1_idx` (`Login_Nick_L` ASC),
  CONSTRAINT `fk_Admon_Usua_Login1`
    FOREIGN KEY (`Login_Nick_L`)
    REFERENCES `mydb`.`Login` (`Nick_L`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdmonU_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdmonU_Usuario` (
  `Renter_Nick_R` INT NOT NULL,
  `Admon_Usua_Nick_AU` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Renter_Nick_R`, `Admon_Usua_Nick_AU`),
  INDEX `fk_AdmonU_Usuario_Admon_Usua1_idx` (`Admon_Usua_Nick_AU` ASC),
  CONSTRAINT `fk_AdmonU_Usuario_Renter1`
    FOREIGN KEY (`Renter_Nick_R`)
    REFERENCES `mydb`.`Usuario` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AdmonU_Usuario_Admon_Usua1`
    FOREIGN KEY (`Admon_Usua_Nick_AU`)
    REFERENCES `mydb`.`Admon_Usua` (`Nick_AU`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delgacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delgacion` (
  `idDel` INT NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  PRIMARY KEY (`idDel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dirección`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dirección` (
  `idDir` INT NOT NULL,
  `Colonia` VARCHAR(50) NULL,
  `C.P.` INT NULL,
  `Calle` VARCHAR(50) NULL,
  `No_int` INT NULL,
  `No_ext` INT NULL,
  `Delgacion_idDel` INT NOT NULL,
  PRIMARY KEY (`idDir`, `Delgacion_idDel`),
  INDEX `fk_Dirección_Delgacion1_idx` (`Delgacion_idDel` ASC),
  CONSTRAINT `fk_Dirección_Delgacion1`
    FOREIGN KEY (`Delgacion_idDel`)
    REFERENCES `mydb`.`Delgacion` (`idDel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_Dir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_Dir` (
  `Renter_Nick_R` INT NOT NULL,
  `Dirección_idDir` INT NOT NULL,
  PRIMARY KEY (`Renter_Nick_R`, `Dirección_idDir`),
  INDEX `fk_Persona_Dir_Dirección1_idx` (`Dirección_idDir` ASC),
  CONSTRAINT `fk_Persona_Dir_Renter`
    FOREIGN KEY (`Renter_Nick_R`)
    REFERENCES `mydb`.`Usuario` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Persona_Dir_Dirección`
    FOREIGN KEY (`Dirección_idDir`)
    REFERENCES `mydb`.`Dirección` (`idDir`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario_Trabajo` (
  `idHT` INT NOT NULL,
  `Dia` VARCHAR(15) NULL,
  `Hora` VARCHAR(15) NULL,
  `Usuario_Nick_U` INT NOT NULL,
  `Usuario_Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idHT`, `Usuario_Nick_U`, `Usuario_Login_Nick_L`),
  INDEX `fk_Horario_Trabajo_Usuario1_idx` (`Usuario_Nick_U` ASC, `Usuario_Login_Nick_L` ASC),
  CONSTRAINT `fk_Horario_Trabajo_Usuario1`
    FOREIGN KEY (`Usuario_Nick_U` , `Usuario_Login_Nick_L`)
    REFERENCES `mydb`.`Usuario` (`Nick_U` , `Login_Nick_L`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona_Trabajo` (
  `idZT` INT NOT NULL,
  `Estado` VARCHAR(25) NULL,
  `Ciudad` VARCHAR(25) NULL,
  `Delegación` VARCHAR(25) NULL,
  PRIMARY KEY (`idZT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner_ZT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner_ZT` (
  `Zona_Trabajo_idZT` INT NOT NULL,
  `Usuario_Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Zona_Trabajo_idZT`, `Usuario_Login_Nick_L`),
  INDEX `fk_Owner_ZT_Zona_Trabajo1_idx` (`Zona_Trabajo_idZT` ASC),
  INDEX `fk_Owner_ZT_Usuario1_idx` (`Usuario_Login_Nick_L` ASC),
  CONSTRAINT `fk_Owner_ZT_Zona_Trabajo1`
    FOREIGN KEY (`Zona_Trabajo_idZT`)
    REFERENCES `mydb`.`Zona_Trabajo` (`idZT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Owner_ZT_Usuario`
    FOREIGN KEY (`Usuario_Login_Nick_L`)
    REFERENCES `mydb`.`Usuario` (`Login_Nick_L`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo_Servicios` (
  `idCS` INT NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  PRIMARY KEY (`idCS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `idServicio` INT NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  `Catalogo_Servicios_idCS` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `Catalogo_Servicios_idCS`),
  INDEX `fk_Servicio_Catalogo_Servicios1_idx` (`Catalogo_Servicios_idCS` ASC),
  CONSTRAINT `fk_Servicio_Catalogo_Servicios1`
    FOREIGN KEY (`Catalogo_Servicios_idCS`)
    REFERENCES `mydb`.`Catalogo_Servicios` (`idCS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner_Ser` (
  `Servicio_idServicio` INT NOT NULL,
  `Usuario_Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`, `Usuario_Login_Nick_L`),
  INDEX `fk_Owner_Ser_Servicio1_idx` (`Servicio_idServicio` ASC),
  INDEX `fk_Owner_Ser_Usuario1_idx` (`Usuario_Login_Nick_L` ASC),
  CONSTRAINT `fk_Owner_Ser_Servicio`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Owner_Ser_Usuario`
    FOREIGN KEY (`Usuario_Login_Nick_L`)
    REFERENCES `mydb`.`Usuario` (`Login_Nick_L`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admon_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admon_Ser` (
  `Nick_AS` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  `ApeliidoP` VARCHAR(25) NULL,
  `ApellidoM` VARCHAR(25) NULL,
  `Genero` VARCHAR(15) NULL,
  `Cel` INT NULL,
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick_AS`, `Login_Nick_L`),
  INDEX `fk_Admon_Ser_Login1_idx` (`Login_Nick_L` ASC),
  CONSTRAINT `fk_Admon_Ser_Login`
    FOREIGN KEY (`Login_Nick_L`)
    REFERENCES `mydb`.`Login` (`Nick_L`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contrato` (
  `Clave` VARCHAR(20) NOT NULL,
  `Fecha` DATE NULL,
  `Hora` VARCHAR(15) NULL,
  `Especificaciones` VARCHAR(225) NULL,
  `Clausulas` VARCHAR(225) NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Usuario_Nick_U` INT NOT NULL,
  `Usuario_Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Clave`, `Servicio_idServicio`, `Usuario_Nick_U`, `Usuario_Login_Nick_L`),
  INDEX `fk_Contrato_Servicio1_idx` (`Servicio_idServicio` ASC),
  INDEX `fk_Contrato_Usuario1_idx` (`Usuario_Nick_U` ASC, `Usuario_Login_Nick_L` ASC),
  CONSTRAINT `fk_Contrato_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrato_Usuario1`
    FOREIGN KEY (`Usuario_Nick_U`)
    REFERENCES `mydb`.`Usuario` (`Nick_U`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdmonSer_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdmonSer_Ser` (
  `Servicio_idServicio` INT NOT NULL,
  `Admon_Ser_Nick_AS` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`, `Admon_Ser_Nick_AS`),
  INDEX `fk_AdmonSer_Ser_Admon_Ser1_idx` (`Admon_Ser_Nick_AS` ASC),
  CONSTRAINT `fk_AdmonSer_Ser_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AdmonSer_Ser_Admon_Ser1`
    FOREIGN KEY (`Admon_Ser_Nick_AS`)
    REFERENCES `mydb`.`Admon_Ser` (`Nick_AS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdmonSer_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdmonSer_Contrato` (
  `Contrato_Clave` VARCHAR(20) NOT NULL,
  `Admon_Ser_Nick_AS` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Contrato_Clave`, `Admon_Ser_Nick_AS`),
  INDEX `fk_AdmonSer_Contrato_Admon_Ser1_idx` (`Admon_Ser_Nick_AS` ASC),
  CONSTRAINT `fk_AdmonSer_Contrato_Contrato1`
    FOREIGN KEY (`Contrato_Clave`)
    REFERENCES `mydb`.`Contrato` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AdmonSer_Contrato_Admon_Ser1`
    FOREIGN KEY (`Admon_Ser_Nick_AS`)
    REFERENCES `mydb`.`Admon_Ser` (`Nick_AS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `idTipo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTipo`, `Login_Nick_L`),
  INDEX `fk_Tipo_Login1_idx` (`Login_Nick_L` ASC),
  CONSTRAINT `fk_Tipo_Login`
    FOREIGN KEY (`Login_Nick_L`)
    REFERENCES `mydb`.`Login` (`Nick_L`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
