-- MySQL Script generated by MySQL Workbench
-- Mon Sep 10 01:11:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `Nick_L` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  PRIMARY KEY (`Nick_L`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Nick_U` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Fecha_Nac` DATE NULL,
  `Cel` VARCHAR(45) NULL,
  `Delegacion` VARCHAR(45) NULL,
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick_U`),
  INDEX `fk_Persona_Login1_idx` (`Login_Nick_L` ASC),
  CONSTRAINT `fk_Persona_Login1`
    FOREIGN KEY (`Login_Nick_L`)
    REFERENCES `mydb`.`Login` (`Nick_L`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admon_Usua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admon_Usua` (
  `Nick_AU` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Cel` VARCHAR(45) NULL,
  PRIMARY KEY (`Nick_AU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `idTipo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login_Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login_Tipo` (
  `Login_Nick_L` VARCHAR(15) NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  PRIMARY KEY (`Login_Nick_L`, `Tipo_idTipo`),
  INDEX `fk_Login_Tipo_Tipo1_idx` (`Tipo_idTipo` ASC),
  CONSTRAINT `fk_Login_Tipo_Login1`
    FOREIGN KEY (`Login_Nick_L`)
    REFERENCES `mydb`.`Login` (`Nick_L`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Login_Tipo_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delegacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delegacion` (
  `idDel` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idDel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDir` INT NOT NULL,
  `Colonia` VARCHAR(45) NULL,
  `CP` INT NULL,
  `Calle` VARCHAR(45) NULL,
  `No_int` INT NULL,
  `No_ext` INT NULL,
  `Delegacion_idDel` INT NOT NULL,
  PRIMARY KEY (`idDir`, `Delegacion_idDel`),
  INDEX `fk_Direccion_Delegacion1_idx` (`Delegacion_idDel` ASC),
  CONSTRAINT `fk_Direccion_Delegacion1`
    FOREIGN KEY (`Delegacion_idDel`)
    REFERENCES `mydb`.`Delegacion` (`idDel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_Dir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_Dir` (
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  `Direccion_idDir` INT NOT NULL,
  PRIMARY KEY (`Persona_Nick_U`, `Direccion_idDir`),
  INDEX `fk_Persona_Dir_Direccion1_idx` (`Direccion_idDir` ASC),
  CONSTRAINT `fk_Persona_Dir_Persona1`
    FOREIGN KEY (`Persona_Nick_U`)
    REFERENCES `mydb`.`Persona` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Persona_Dir_Direccion1`
    FOREIGN KEY (`Direccion_idDir`)
    REFERENCES `mydb`.`Direccion` (`idDir`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdmonU_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdmonU_Usuario` (
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  `Admon_Usua_Nick_AU` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Persona_Nick_U`, `Admon_Usua_Nick_AU`),
  INDEX `fk_AdmonU_Usuario_Admon_Usua1_idx` (`Admon_Usua_Nick_AU` ASC),
  CONSTRAINT `fk_AdmonU_Usuario_Persona1`
    FOREIGN KEY (`Persona_Nick_U`)
    REFERENCES `mydb`.`Persona` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AdmonU_Usuario_Admon_Usua1`
    FOREIGN KEY (`Admon_Usua_Nick_AU`)
    REFERENCES `mydb`.`Admon_Usua` (`Nick_AU`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `Nick_O` VARCHAR(15) NOT NULL,
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick_O`, `Persona_Nick_U`),
  INDEX `fk_Owner_Persona1_idx` (`Persona_Nick_U` ASC),
  CONSTRAINT `fk_Owner_Persona1`
    FOREIGN KEY (`Persona_Nick_U`)
    REFERENCES `mydb`.`Persona` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo_Servicios` (
  `idCS` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `idServicio` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Catalogo_Servicios_idCS` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `Catalogo_Servicios_idCS`),
  INDEX `fk_Servicio_Catalogo_Servicios1_idx` (`Catalogo_Servicios_idCS` ASC),
  CONSTRAINT `fk_Servicio_Catalogo_Servicios1`
    FOREIGN KEY (`Catalogo_Servicios_idCS`)
    REFERENCES `mydb`.`Catalogo_Servicios` (`idCS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner_Ser` (
  `Owner_Nick_O` VARCHAR(15) NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`Owner_Nick_O`, `Servicio_idServicio`),
  INDEX `fk_Owner_Ser_Servicio1_idx` (`Servicio_idServicio` ASC),
  CONSTRAINT `fk_Owner_Ser_Owner1`
    FOREIGN KEY (`Owner_Nick_O`)
    REFERENCES `mydb`.`Owner` (`Nick_O`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Owner_Ser_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admon_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admon_Ser` (
  `Nick_AS` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Cel` VARCHAR(45) NULL, 
  PRIMARY KEY (`Nick_AS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdmonSer_Ser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdmonSer_Ser` (
  `Servicio_idServicio` INT NOT NULL,
  `Admon_Ser_Nick_AS` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`, `Admon_Ser_Nick_AS`),
  INDEX `fk_AdmonSer_Ser_Admon_Ser1_idx` (`Admon_Ser_Nick_AS` ASC),
  CONSTRAINT `fk_AdmonSer_Ser_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AdmonSer_Ser_Admon_Ser1`
    FOREIGN KEY (`Admon_Ser_Nick_AS`)
    REFERENCES `mydb`.`Admon_Ser` (`Nick_AS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona_Trabajo` (
  `idZT` INT NOT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Delegaciòn` VARCHAR(45) NULL,
  PRIMARY KEY (`idZT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner_ZT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner_ZT` (
  `Owner_Nick_O` VARCHAR(15) NOT NULL,
  `Zona_Trabajo_idZT` INT NOT NULL,
  PRIMARY KEY (`Owner_Nick_O`, `Zona_Trabajo_idZT`),
  INDEX `fk_Owner_ZT_Zona_Trabajo1_idx` (`Zona_Trabajo_idZT` ASC),
  CONSTRAINT `fk_Owner_ZT_Owner1`
    FOREIGN KEY (`Owner_Nick_O`)
    REFERENCES `mydb`.`Owner` (`Nick_O`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Owner_ZT_Zona_Trabajo1`
    FOREIGN KEY (`Zona_Trabajo_idZT`)
    REFERENCES `mydb`.`Zona_Trabajo` (`idZT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Renter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Renter` (
  `Nick_R` VARCHAR(15) NOT NULL,
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick_R`, `Persona_Nick_U`),
  INDEX `fk_Renter_Persona1_idx` (`Persona_Nick_U` ASC),
  CONSTRAINT `fk_Renter_Persona1`
    FOREIGN KEY (`Persona_Nick_U`)
    REFERENCES `mydb`.`Persona` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contrato` (
  `Clave` VARCHAR(20) NOT NULL,
  `Fecha` DATE NULL,
  `Hora` VARCHAR(45) NULL,
  `Especificaciones` VARCHAR(225) NULL,
  `Clausulas` VARCHAR(225) NULL,
  `Renter_Nick_R` VARCHAR(15) NOT NULL,
  `Renter_Persona_Nick_U` VARCHAR(15) NOT NULL,
  `Owner_Nick_O` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Clave`, `Renter_Nick_R`, `Renter_Persona_Nick_U`, `Owner_Nick_O`),
  INDEX `fk_Contrato_Renter1_idx` (`Renter_Nick_R` ASC, `Renter_Persona_Nick_U` ASC),
  INDEX `fk_Contrato_Owner1_idx` (`Owner_Nick_O` ASC),
  CONSTRAINT `fk_Contrato_Renter1`
    FOREIGN KEY (`Renter_Nick_R` , `Renter_Persona_Nick_U`)
    REFERENCES `mydb`.`Renter` (`Nick_R` , `Persona_Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrato_Owner1`
    FOREIGN KEY (`Owner_Nick_O`)
    REFERENCES `mydb`.`Owner` (`Nick_O`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdmonSer_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdmonSer_Contrato` (
  `Admon_Ser_Nick_AS` VARCHAR(15) NOT NULL,
  `Contrato_Clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Admon_Ser_Nick_AS`, `Contrato_Clave`),
  INDEX `fk_AdmonSer_Contrato_Contrato1_idx` (`Contrato_Clave` ASC),
  CONSTRAINT `fk_AdmonSer_Contrato_Admon_Ser1`
    FOREIGN KEY (`Admon_Ser_Nick_AS`)
    REFERENCES `mydb`.`Admon_Ser` (`Nick_AS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AdmonSer_Contrato_Contrato1`
    FOREIGN KEY (`Contrato_Clave`)
    REFERENCES `mydb`.`Contrato` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario_Trabajo` (
  `idHT` INT NOT NULL,
  `Dia` VARCHAR(45) NULL,
  `Hora` VARCHAR(45) NULL,
  `Owner_Nick_O` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idHT`, `Owner_Nick_O`),
  INDEX `fk_Horario_Trabajo_Owner1_idx` (`Owner_Nick_O` ASC),
  CONSTRAINT `fk_Horario_Trabajo_Owner1`
    FOREIGN KEY (`Owner_Nick_O`)
    REFERENCES `mydb`.`Owner` (`Nick_O`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Queja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Queja` (
  `id_Queja` INT NOT NULL,
  `Descripcion` VARCHAR(400) NULL,
  `Contrato_Clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Queja`, `Contrato_Clave`),
  INDEX `fk_Queja_Contrato1_idx` (`Contrato_Clave` ASC),
  CONSTRAINT `fk_Queja_Contrato1`
    FOREIGN KEY (`Contrato_Clave`)
    REFERENCES `mydb`.`Contrato` (`Clave`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `idPago` INT NOT NULL,
  `Banco` VARCHAR(45) NULL,
  `Fecha` VARCHAR(45) NULL,
  `Monto` VARCHAR(45) NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo_Tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo_Tarjetas` (
  `id_Tar` INT NOT NULL,
  `Pago_idPago` INT NOT NULL,
  `Persona_Nick_U` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Pago_idPago`, `Persona_Nick_U`, `id_Tar`),
  INDEX `fk_Catalogo_Tarjetas_Pago1_idx` (`Pago_idPago` ASC),
  INDEX `fk_Catalogo_Tarjetas_Persona1_idx` (`Persona_Nick_U` ASC),
  CONSTRAINT `fk_Catalogo_Tarjetas_Pago1`
    FOREIGN KEY (`Pago_idPago`)
    REFERENCES `mydb`.`Pago` (`idPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Catalogo_Tarjetas_Persona1`
    FOREIGN KEY (`Persona_Nick_U`)
    REFERENCES `mydb`.`Persona` (`Nick_U`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LoginTipo_Quejas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LoginTipo_Quejas` (
  `Queja_id_Queja` INT NOT NULL,
  `Login_Tipo_Login_Nick_L` VARCHAR(15) NOT NULL,
  `Login_Tipo_Tipo_idTipo` INT NOT NULL,
  PRIMARY KEY (`Queja_id_Queja`, `Login_Tipo_Login_Nick_L`, `Login_Tipo_Tipo_idTipo`),
  INDEX `fk_LoginTipo_Quejas_Login_Tipo1_idx` (`Login_Tipo_Login_Nick_L` ASC, `Login_Tipo_Tipo_idTipo` ASC),
  CONSTRAINT `fk_LoginTipo_Quejas_Queja1`
    FOREIGN KEY (`Queja_id_Queja`)
    REFERENCES `mydb`.`Queja` (`id_Queja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LoginTipo_Quejas_Login_Tipo1`
    FOREIGN KEY (`Login_Tipo_Login_Nick_L` , `Login_Tipo_Tipo_idTipo`)
    REFERENCES `mydb`.`Login_Tipo` (`Login_Nick_L` , `Tipo_idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
